apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: 262194309205.dkr.ecr.eu-west-2.amazonaws.com/chatapp-django:latest
          envFrom:
            - configMapRef:
                name: chatapp-config
            - secretRef:
                name: chatapp-secret
          ports:
            - containerPort: 8000
# Health checks
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
