apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: 262194309205.dkr.ecr.eu-west-2.amazonaws.com/chatapp-mysql:latest
          envFrom:
            - configMapRef:
                name: chatapp-config
            - secretRef:
                name: chatapp-secret
          ports:
            - containerPort: 3306

# Health Checks
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 2
# in readiness  successThreshold can 2 or more than two but in this it should be exactly 1
# successThreshold > 1 makes sense for readiness/startup (ensure app is stable before accepting traffic)
#But for liveness, once a probe passes, the app is considered healthy — no need to double-confirm

