apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: 262194309205.dkr.ecr.eu-west-2.amazonaws.com/chatapp-nginx:latest
          ports:
            - containerPort: 80
